# trigger deploy
name: Deploy Node.js application to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Build backend application (if applicable)
        run: npm run build
        working-directory: ./backend

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 44.212.4.6
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # ✅ EC2 서버에 프로젝트 디렉토리 이동 또는 클론
            cd /home/ubuntu/

            if [ ! -d "back_schedule_planner" ]; then
              git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/seominji58/back_schedule_planner.git
            else
              cd back_schedule_planner
              git pull origin main
            fi

            cd /home/ubuntu/back_schedule_planner/backend

            # ✅ .env 파일 생성
            cat <<EOF > .env
FIREBASE_TYPE=${{ secrets.FIREBASE_TYPE }}
FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
FIREBASE_PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
FIREBASE_PRIVATE_KEY="${{ secrets.FIREBASE_PRIVATE_KEY }}"
FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}
FIREBASE_CLIENT_ID=${{ secrets.FIREBASE_CLIENT_ID }}
FIREBASE_AUTH_URI=${{ secrets.FIREBASE_AUTH_URI }}
FIREBASE_TOKEN_URI=${{ secrets.FIREBASE_TOKEN_URI }}
FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}
FIREBASE_CLIENT_X509_CERT_URL=${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}
FIREBASE_UNIVERSE_DOMAIN=${{ secrets.FIREBASE_UNIVERSE_DOMAIN }}

PORT=${{ secrets.PORT }}
NODE_ENV=${{ secrets.NODE_ENV }}
LOG_LEVEL=${{ secrets.LOG_LEVEL }}
LOG_FILE=${{ secrets.LOG_FILE }}
CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
RATE_LIMIT_WINDOW_MS=${{ secrets.RATE_LIMIT_WINDOW_MS }}
RATE_LIMIT_MAX_REQUESTS=${{ secrets.RATE_LIMIT_MAX_REQUESTS }}

GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}
GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}

JWT_SECRET=${{ secrets.JWT_SECRET }}
OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
EOF

            # ✅ 의존성 설치
            npm install

            # ✅ 서버 실행 또는 재시작
            pm2 list | grep "schedule-planner-backend"
            if [ $? -eq 0 ]; then
              pm2 restart schedule-planner-backend --update-env
            else
              pm2 start dist/server.js --name schedule-planner-backend --env production
            fi

            pm2 save
